version: '3.1'
services:
  token:
    image: node:8.9
    working_dir: /app
    expose:
      - 3000
    volumes:
      - .//:/app
    command: npm start
    environment:
      - TOKEN_SERVICE_HOST=0.0.0.0
      - SWAGGER_URL=localhost:8182
    ports:
      - 3000:3000
